import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./index.css";

import Sidebar from "@/components/sidebar";
import SupabaseProvider from "@/providers/SupabaseProvider";
import UserProvider from "@/providers/UserProvider";
import ModalProvider from "@/providers/ModalProvider";
import { Toaster } from "@/components/ui/toaster";
import Player from "@/components/Player";
import getPlaylistById from "@/actions/getPlaylistById";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify Clone",
  description: "Generated by create next app",
};
export const revalidate = 0;
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userPlaylist = await getPlaylistById();
  return (
    <html lang="en">
      <body>
        <Toaster />
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider />
            <Sidebar playlists={userPlaylist}>{children}</Sidebar>
            <Player />
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
